server:
  port: 8001

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drug_store?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:
    service-url:
      defaultZone: http://xxin:xxin@localhost:8761/eureka, http://xxin:xxin@localhost:8762/eureka
